AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sudoku-solver

Globals:
  Function:
    Timeout: 5
    MemorySize: 128MB

Resources:
  SolveSudokuStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/sudoku-solver.asl.json
      DefinitionSubstitutions:
        ValidSudokuFunctionArn: !GetAtt ValidSudokuFunction.Arn
        SudokuSolverFunctionArn: !GetAtt SudokuSolverFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ValidSudokuFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SudokuSolverFunction

  ValidSudokuFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/functions/valid-sudoku
      Handler: bootstrap
      Runtime: provided.al2

  SudokuSolverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/functions/sudoku-solver
      Handler: bootstrap
      Runtime: provided.al2
